version: '3.4'

services:
    web:
        container_name: web
        image: nginx:latest
        depends_on:
            - php
            - db
        domainname: "sfcollection.local"
        networks:
            mynet:
                aliases:
                    - web.sfcollection.local
        volumes:
            - ./docker/nginx/site.template:/etc/nginx/conf.d/site.template
            - .:/app:cached
        command: >
            /bin/bash -c
            "envsubst '$$NGINX_HOST $$NGINX_PORT $$NGINX_ROOT'
            < /etc/nginx/conf.d/site.template
            > /etc/nginx/conf.d/default.conf
            && exec nginx -g 'daemon off;'"
        ports:
            - "8080:80"
        environment:
            NGINX_HOST: "sfcollection.local"
            NGINX_PORT: 80
            NGINX_ROOT: "/app/public"
    php:
        build:
            context: ./docker/php
            args:
                - PHP_VERSION=7.2
        depends_on:
            - db
        links:
            - db
        networks:
            mynet:
                aliases:
                    - php.sfcollection.local
        volumes:
            - ./:/app:rw
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        restart: always
    db:
        image: mariadb:latest
        restart: always
        volumes:
            - mariadb:/var/lib/mysql:rw
            - ./docker/mariadb:/etc/mysql/conf.d
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sfcollection
            MYSQL_USER: sfcollection
            MYSQL_PASSWORD: sfcollection
        networks:
            mynet:
                aliases:
                    - db.sfcollection.local
networks:
    mynet:
volumes:
    mariadb:
    cache:
